### ISSUE TITLE
sympy.stats

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy-paper#16] opened 2016-03-18 17:39 UTC
We have a very nice submodule (_sympy.stats_).

@mrocklin has already published something related:
- http://people.cs.uchicago.edu/~mrocklin/tempspace/scipy2012-sympystats-paper.pdf
- https://www.computer.org/cms/ComputingNow/homepage/2012/0712/W_CS_SymbolicStatisticswithSymPy.pdf

I'd suggest to put a short description with proper citations.

**Comment by sumith1896** [comment] 2016-05-17 20:54
Duplicate of https://github.com/sympy/sympy-paper/issues/126

**Closed as completed by sumith1896** 2016-05-17 20:54 UTC
